version: "3.9"

services:
  db:
    image: postgres:15
    container_name: event-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    container_name: event-server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: event_app
      JWT_SECRET: supersecretkey

  client:
    build: ./client
    container_name: event-client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  db_data:
